Copy the packages one by one
Copying multiple packages at once causes

  lazr.restfulclient.errors.ServerError: HTTP Error 503: Service Unavailable

(x-lazr-oopsid: OOPS-d1ee664e50863437a6a9c2b357e783c4 for reference, the
response body says "Error: Timeout" among a bunch of HTML.)